import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import catalogRoutes from '../modules/catalog/catalog.routes.js';
import studentRoutes from '../modules/students/students.routes.js';
import enrollmentRoutes from '../modules/enrollments/enrollments.routes.js';
import sectionRoutes from '../modules/sections/sections.routes.js';
import gradeRoutes from '../modules/grades/grades.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import clearanceRoutes from '../modules/clearance/clearance.routes.js';
import calendarRoutes from '../modules/calendar/calendar.routes.js';
import chatRoutes from '../modules/chat/chat.routes.js';
import otpRoutes from '../modules/otp/otp.routes.js';
import ohsRoutes from '../modules/ohs/ohs.routes.js';
import oscdRoutes from '../modules/oscd/oscd.routes.js';
import osaRoutes from '../modules/osa/osa.routes.js';
import faasgRoutes from '../modules/faasg/faasg.routes.js';
import cashieringRoutes from '../modules/cashiering/cashiering.routes.js';

export const routes = Router();

routes.use('/auth', authRoutes);
routes.use('/catalog', catalogRoutes);
routes.use('/students', studentRoutes);
routes.use('/enrollments', enrollmentRoutes);
routes.use('/sections', sectionRoutes);
routes.use('/grades', gradeRoutes);
routes.use('/analytics', analyticsRoutes);
routes.use('/admin', adminRoutes);
routes.use('/clearances', clearanceRoutes);
routes.use('/calendar', calendarRoutes);
routes.use('/chat', chatRoutes);
routes.use('/otp', otpRoutes);
routes.use('/ohs', ohsRoutes);
routes.use('/oscd', oscdRoutes);
routes.use('/osa', osaRoutes);
routes.use('/faasg', faasgRoutes);
routes.use('/cashiering', cashieringRoutes);